### ISSUE TITLE
allow to change status server port

### ISSUE THREAD

**Issue by 7flash** [chiselstrike/chiselstrike#1479] opened 2022-06-24 05:56 UTC
currently it conflicts with other applications running

![image](https://user-images.githubusercontent.com/4569866/175471794-57a20b49-66f0-42f8-af56-13e4fb7d53e3.png)

https://github.com/chiselstrike/chiselstrike/pull/362

**Comment by 7flash** [comment] 2022-06-24 05:58
it actually seems port already taken buy chisel.. that is more weird..

![image](https://user-images.githubusercontent.com/4569866/175471989-7a5be4f2-e5f9-4410-8762-2e8f954c12d8.png)

**Comment by 7flash** [comment] 2022-06-24 05:58
trying to run boilerplate app with pm2..

```
pm2 start "npm run dev"
```

**Comment by penberg** [comment] 2022-06-24 06:05
The issue is likely that `chisel dev` died but forgot to kill the background daemon `chiseld`. This is fixed in `main` but not yet released. Just run `killall -9 chiseld` and that should fix the issue. Let's keep the issue open though as that error message needs fixing.

**Comment by 7flash** [comment] 2022-06-24 06:09
thanks for rapid response.. just did that and restarted again.. the same situation.. seems it's not compatible with pm2.. it actually remains working in background.. but pm2 shows an error..

**Comment by penberg** [comment] 2022-06-24 06:50
@BearLemma @espindola can one of you try out ChiselStrike with https://pm2.keymetrics.io and see what the issue is?

**Comment by 7flash** [comment] 2022-06-24 21:34
Anyway what's the correct way to deploy in production to my server..

**Comment by glommer** [comment] 2022-06-24 22:56
@7flash can you confirm you are building from git or using a released version?
I just tested with pm2 and it works for me.

For production, I wouldn't recommend using the "run dev" workflow anyway: that workflow is a development mode (as the name implies) helper that listen for files in the local directory where it is called, and apply them automatically as changed.

If you spawned a daemon, those don't go well together.


It is probably better to do `pm2 start "npx chisel start"

the process is now running:

```
glauber          98460   0.0  0.2 408549664  27680   ??  S     6:54pm   0:00.06 node /opt/homebrew/bin/chisel start
```

as can be verified by checking the status:

```
npx chisel status
Server status is OK
```

And you can `apply` the local files manually when there is a change:

```
npx chisel apply
End point defined: /dev/hello
```

This should work much better since `chisel dev` will also daemonize and spawn a new server, which will likely conflict with what pm2 is trying to do.

Hope that was useful, and if you're not around already, we'd love to have you at our discord channel https://discord.gg/GHNN9CNAZe

**Comment by 7flash** [comment] 2022-06-25 00:07
Thanks for detailed explanation.. that works well.. should be added into docs..

```
pm2 start "npx chisel start" --name board-dapp-second --no-autorestart
```

![image](https://user-images.githubusercontent.com/4569866/175750095-04e2598b-be0f-4e17-b933-3013f97f0bd1.png)

**Comment by 7flash** [comment] 2022-06-25 00:08
regarding the original issue.. it solves the problem for me.. but still might be needed to be able choose custom port..

**Comment by glommer** [comment] 2022-06-25 01:47
100%. Let me know if you'd be interested in sending a PR to change the readme and/or the port option. It would be awesome  to have your contribution!

If not, I'll try to get to this soon over the weekend.

**Comment by 7flash** [comment] 2022-06-25 07:07
Sure will try.. it seems default port defined here.. just need to figure out how to read it from cmd opts..

https://github.com/chiselstrike/chiselstrike/blob/740c941bf69b0245680fd5a4733e21aac76eba67/server/src/server.rs#L46

**Comment by espindola** [comment] 2022-06-27 09:34
We already have --api-listen-addr, --internal-routes-listen-addr e --rpc-listen-addr. We just need to make it easy to pass them via the cli (issue #1481), right?

**Comment by 7flash** [comment] 2022-06-28 12:25
no couldn't find those arguments you mentioned in codebase..

**Comment by 7flash** [comment] 2022-06-28 12:25
should be passing an argument here in CLI app.. https://github.com/chiselstrike/chiselstrike/blob/8c7903548e0198d0ded4b03243e3b894b6d4503e/cli/src/server.rs#L12

**Comment by dekimir** [comment] 2022-06-28 14:59
> no couldn't find those arguments you mentioned in codebase..

Perhaps you did, and never realized it.  Your [comment above](https://github.com/chiselstrike/chiselstrike/issues/1479#issuecomment-1166209917) shows them in the codebase.  `structopt` will automatically make that a CLI option (of `chiseld`), except with dashes instead of underscores.

**Comment by glommer** [comment] 2022-06-28 19:54
@7flash As Dejan explained, this is done through structopts. So When we do this:

```
    #[structopt(short, long, default_value = "127.0.0.1:9090")]
    internal_routes_listen_addr: SocketAddr,
```

the structopt proc macro automatically generates the option `--internal-routes-listen-addr` that you can now set.
This won't get passed to `chisel dev`, but it seems like you are not going for it anymore, since you are using this through `pm2`.

In that case, I believe this is solved for you, right?

BTW, If you're not on our discord, would love to chat! drop by! (If you are, feel free to shoot me a message)

**Comment by glommer** [comment] 2022-06-28 19:55
I am closing with the understanding that the option is already there, and passing them to `chisel dev` is not the goal. @7flash let me know if there still anything pending and we'll get to it!

**Closed by glommer** 2022-06-28 19:55 UTC

**Comment by 7flash** [comment] 2022-06-28 22:20
```
../target/debug/chisel dev --internal-routes-listen-addr=9091
```
>>
error: Found argument '--internal-routes-listen-addr' which wasn't expected, or isn't valid in this context

**Comment by 7flash** [comment] 2022-06-28 22:22
```
../target/debug/chisel start --internal-routes-listen-addr=127.0.0.1:9091
```

error: Found argument '--internal-routes-listen-addr' which wasn't expected, or isn't valid in this context

**Comment by glommer** [comment] 2022-06-28 22:27
Right. As I said, those arguments are not passed to `dev` (none of the port ones are), but I thought it should work with `chisel start`. Turns out it doesn't, it works only if you invoke the server directly.

I'll open another, more generic issue.

In the meantime, since you are compiling it anyway, try to start the server directly:
```
./target/debug/chiseld --internal-routes-listen-addr=127.0.0.1:9091
```

(`chisel` is the command line utility that controls the server `chiseld` )
