### ISSUE TITLE
can't import jsonwebtoken through esbuild (node mode)

### ISSUE THREAD

**Issue by glommer** [chiselstrike/chiselstrike#1051] opened 2022-03-29 18:17 UTC
endpoint:

```
import * as jwt from "jsonwebtoken";
import { responseFromJson } from "@chiselstrike/api"

export default async function chisel(req: Request) {
   var token = jwt.sign({ foo: 'bar' }, 'shhhhh');
  return new responseFromJson(token);
}
```

Result:

```
Error: parsing endpoint /dev/count

Caused by:
    Error: Dynamic require of "buffer" is not supported
        at file:///dev/count.js?ver=1:12:9
        at node_modules/safe-buffer/index.js (file:///dev/count.js?ver=1:30:18)
        at __require2 (file:///dev/count.js?ver=1:15:50)
        at node_modules/jws/lib/sign-stream.js (file:///dev/count.js?ver=1:561:19)
        at __require2 (file:///dev/count.js?ver=1:15:50)
        at node_modules/jws/index.js (file:///dev/count.js?ver=1:741:22)
        at __require2 (file:///dev/count.js?ver=1:15:50)
        at node_modules/jsonwebtoken/decode.js (file:///dev/count.js?ver=1:774:15)
        at __require2 (file:///dev/count.js?ver=1:15:50)
        at node_modules/jsonwebtoken/index.js (file:///dev/count.js?ver=1:2832:15)
```

Because we are able to import jsonwebtoken as a deno module, the issue here is certainly other. Could be esbuild specific, but most likely, due to the mention of "buffer", could be lack of node globals.

**Comment by penberg** [comment] 2022-08-24 09:11
Duplicate of https://github.com/chiselstrike/chiselstrike/issues/1530 that has more discussion, closing.

**Closed by penberg** 2022-08-24 09:11 UTC
Labels: bug, developer experience
