### ISSUE TITLE
Dynamic require of "buffer" is not supported

### ISSUE THREAD

**Issue by honzasp** [chiselstrike/chiselstrike#1530] opened 2022-07-07 15:24 UTC
When I add the `memfs` package to `package.json` and import it (`import ... from memfs`), I get the following error:

```
> bomb@1.0.0 dev
> chisel dev

[2022-07-07T15:20:12Z] INFO - ChiselStrike is ready 🚀 - URL: http://localhost:8080 
Unhandled exception: Error: Promise rejected without a handler: Error: Dynamic require of "buffer" is not supported
    at file:///worker.js:6:15
parsing endpoints

Caused by:
    Error: Dynamic require of "buffer" is not supported
```

Steps to reproduce:
- Run `npx -y create-chiselstrike-app bomb`
- Add `"memfs": "^3.4.7"` to `"dependencies"` in `package.json`
- Run `npm install`
- Replace `endpoints/hello.ts` with the following
```typescript
import memfs from 'memfs';

export default async function (req: Request): Promise<Response> {
    return new Response(memfs.Volume);
}
```
- Start the backend with `npm run dev`

**Comment by espindola** [comment] 2022-07-08 10:29
When testing this in deno mode, it hits https://github.com/ije/esm.sh/issues/363.

It is interesting that deno produces different errors for x-typescript-types and `@deno-types`. My understanding is that they should be equivalent. I will investigate where the difference is coming from and it is a feature or a bug.

A long standing TODO is to refactor the deno code into a deno-tsc crate and use that both in deno and chiselstrike. I guess I should bump the priority of that item.

**Comment by espindola** [comment] 2022-07-09 09:25
Also reported https://github.com/denoland/deno/issues/15132

**Comment by penberg** [comment] 2022-08-24 06:27
Nevera on Discord says that this issue blocks `axios` and `jsonwebtokens` too, which makes this a high priority.

I see we have an ticket open on `jsonwebtokens` (although I thought it was stale until now): https://github.com/chiselstrike/chiselstrike/issues/1051

**Comment by penberg** [comment] 2022-08-24 06:32
Here's a simple reproducer for axios:

```
import axios from 'axios';

export default async function (req: Request): Promise<string> {
    return await axios.get("www.google.com");
}
```

```
Unhandled exception: Error: Promise rejected without a handler: Error: Dynamic require of "util" is not supported
    at file:///worker.js:6:15
could not import endpoint code into the runtime

Caused by:
    Error: Dynamic require of "util" is not supported
        at file:///dev/endpoints/hello:12:9
        at node_modules/combined-stream/lib/combined_stream.js (file:///dev/endpoints/hello:1751:16)
        at __require2 (file:///dev/endpoints/hello:15:50)
        at node_modules/form-data/lib/form_data.js (file:///dev/endpoints/hello:10766:26)
        at __require2 (file:///dev/endpoints/hello:15:50)
        at node_modules/axios/lib/defaults/env/FormData.js (file:///dev/endpoints/hello:11079:22)
        at __require2 (file:///dev/endpoints/hello:15:50)
        at node_modules/axios/lib/defaults/index.js (file:///dev/endpoints/hello:11175:19)
        at __require2 (file:///dev/endpoints/hello:15:50)
        at node_modules/axios/lib/core/transformData.js (file:///dev/endpoints/hello:11201:20)
```

**Comment by honzasp** [comment] 2022-08-24 06:47
The issue is that we use `esbuild` in `chisel apply` to bundle user code into a single module (if `modules = "node"`), but the bundler cannot resolve an import of the `"buffer"` module, so it translates that import into a `require("buffer")`, which fails at runtime.

**Comment by penberg** [comment] 2022-08-24 06:49
@honzasp Right, there seems to be a way to work around this in `esbuild`:

https://github.com/evanw/esbuild/issues/1921#issuecomment-1166291751

However, hooking that into Node apply path:

```
diff --git a/cli/src/cmd/apply/node.rs b/cli/src/cmd/apply/node.rs
index 1da62f5d..2812ed91 100644
--- a/cli/src/cmd/apply/node.rs
+++ b/cli/src/cmd/apply/node.rs
@@ -132,6 +132,7 @@ pub(crate) async fn apply(
         "--tree-shaking=true".to_string(),
         "--tsconfig=./tsconfig.json".to_string(),
         "--platform=node".to_string(),
+        "--banner:js=\"import { createRequire } from 'module';const require = createRequire(import.meta.url);\"".to_string(),
     ]);

     bundler_cmd_args.push(format!("--outdir={}", bundler_output_dir_name.display()));
```

doesn't seem to change anything:

```
Unhandled exception: Error: Promise rejected without a handler: Error: Dynamic require of "util" is not supported
    at file:///worker.js:5:15
could not import endpoint code into the runtime

Caused by:
    Error: Dynamic require of "util" is not supported
        at file:///dev/endpoints/hello:13:9
        at node_modules/combined-stream/lib/combined_stream.js (file:///dev/endpoints/hello:1752:16)
        at __require2 (file:///dev/endpoints/hello:16:50)
        at node_modules/form-data/lib/form_data.js (file:///dev/endpoints/hello:10767:26)
        at __require2 (file:///dev/endpoints/hello:16:50)
        at node_modules/axios/lib/defaults/env/FormData.js (file:///dev/endpoints/hello:11080:22)
        at __require2 (file:///dev/endpoints/hello:16:50)
        at node_modules/axios/lib/defaults/index.js (file:///dev/endpoints/hello:11176:19)
        at __require2 (file:///dev/endpoints/hello:16:50)
        at node_modules/axios/lib/core/transformData.js (file:///dev/endpoints/hello:11202:20)
```

**Comment by penberg** [comment] 2022-08-24 07:42
The workaround did not work because I passed the JavaScript code incorrectly (it became a string). With this:

```
@@ -132,6 +132,7 @@ pub(crate) async fn apply(
         "--tree-shaking=true".to_string(),
         "--tsconfig=./tsconfig.json".to_string(),
         "--platform=node".to_string(),
+        "--banner:js=import { createRequire } from 'module';const require = createRequire(import.meta.url);".to_string(),
     ]);
 
     bundler_cmd_args.push(format!("--outdir={}", bundler_output_dir_name.display()));
```

I now see this:

```
penberg@vonneumann axios-test % ../chiselstrike/target/debug/chisel apply
Error: could not import endpoint code into the runtime

Caused by:
    TypeError: Relative import path "module" not prefixed with / or ./ or ../ from "file:///dev/endpoints/hello"
        at async importEndpointsImpl (file:///worker.js:50:21)
        at async handleMsg (file:///worker.js:22:17)
```

And that's because we're in Deno land and we can't import a Node module like that.

**Comment by penberg** [comment] 2022-08-24 08:34
I discussed this with @honzasp and the way to fix this is to include the Deno compat library. There are two ways to do this: (1) bundle it in `chiseld` and use the workaround above to allow dynamic loading and (2) similar to `deno run`, *download* the libraries at `chisel apply` time so that `esbuild` sees them while bundling.

**Comment by penberg** [comment] 2022-08-24 08:35
Btw please note that for Axios specifically, there's also a bug on Deno compat that will block from using it: https://github.com/denoland/deno_std/issues/2555

**Comment by penberg** [comment] 2022-08-24 09:10
There's also a Deno issue with using jsonwebtoken: https://github.com/denoland/deno_std/issues/2557

**Comment by 7flash** [comment] 2022-08-26 09:31
Same issue with ethers library

https://github.com/ethers-io/ethers.js/discussions/2892

**Comment by 7flash** [comment] 2022-08-26 09:52
https://github.com/ensdomains/ensjs-v3/issues/40

**Comment by penberg** [comment] 2022-09-23 06:23
This is fixed by https://github.com/chiselstrike/chiselstrike/pull/1783.

@7flash I am closing this issue, but please do open new ones if you hit more problems with other packages.

**Closed** 2022-09-23 06:35 UTC
Labels: bug, developer experience
