### ISSUE TITLE
handler async side effects

### ISSUE THREAD

**Issue by 7flash** [chiselstrike/chiselstrike#1708] opened 2022-08-26 09:34 UTC
When I do setTimeout within handler it never gets executed

```
export default async function chisel(req: ChiselRequest) {
      setTimeout(async () => {
        console.log("This is not executed (unfortunately)")
      }, 100);
      
      return response({});
}
```

**Comment by 7flash** [comment] 2022-09-01 08:50
https://github.com/chiselstrike/chiselstrike/pull/1705

**Comment by glommer** [comment] 2022-09-05 19:01
I think the problem here is that the function returns right away, which cancels the promise.
In fact, we have tests in tree that use `setTimeout`, but it is used differently:


```
    await new Promise(resolve => setTimeout(resolve, 100));
```

Notice that you are at this point creating a promise, and waiting on it.

If your endpoint is this:

```
export default async function (req: Request): Promise<string> {
     setTimeout(async () => {
        console.log("This not executed (fortunately)")
      }, 100); <== this gets registered for later execution

      await new Promise(resolve => setTimeout(resolve, 10000)); <=== but stuff that happens later makes sure that this endpoints lives for more than 100.
      return "";
}

```

IOW, this seems to be just the normal expected behavior of the endpoint terminating before a non-awaited timeout gets a chance to execute.

I'l closing, but let me know if you think I am missing something!

**Closed by glommer** 2022-09-05 19:01 UTC
Labels: bug
